In [6]:
!pip install google-cloud-bigquery pandas --quiet

In [7]:
from google.colab import auth
auth.authenticate_user()

In [8]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client()

In [9]:
from google.colab import auth
auth.authenticate_user()

from google.cloud import bigquery
import pandas as pd


client = bigquery.Client(project="smartsupply-ai")

In [10]:
from google.cloud import bigquery

project_id = "smartsupply-ai"
client = bigquery.Client(project=project_id)

In [11]:
query = """
SELECT *
FROM `smartsupply-ai.smartsupply.shipments`
"""

df = client.query(query).to_dataframe()

df.head()

,ID,Project Code,PQ #,PO _ SO #,ASN_DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure _Per Pack_,Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight _Kilograms_,Freight Cost _USD_,Line Item Insurance _USD_
0,7983,113-ZW-T01,Pre-PQ Process,SCMS-231,ASN-139,Zimbabwe,PMO - US,Direct Drop,CIP,Air,...,60,425,10837.50,25.50,0.42,"BMS Meymac, France",True,Weight Captured Separately,Freight Included in Commodity Cost,NaN
1,68,113-ZW-T01,Pre-PQ Process,SCMS-308,ASN-285,Zimbabwe,PMO - US,Direct Drop,CIP,Air,...,60,579,14764.50,25.50,0.42,"BMS Meymac, France",True,Weight Captured Separately,Freight Included in Commodity Cost,NaN
2,6671,104-CI-T01,Pre-PQ Process,SCMS-609,ASN-704,Côte d'Ivoire,PMO - US,Direct Drop,CIP,Air,...,60,5721,145885.50,25.50,0.42,"BMS Meymac, France",True,1232,Freight Included in Commodity Cost,233.42
3,108,104-CI-T01,Pre-PQ Process,SCMS-698,ASN-727,Côte d'Ivoire,PMO - US,Direct Drop,CIP,Air,...,60,5513,140581.50,25.50,0.42,"BMS Meymac, France",True,2126,Freight Included in Commodity Cost,224.93
4,1245,100-CI-T01,Pre-PQ Process,SCMS-1,ASN-5,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,40,147,11076.45,75.35,1.88,Bio-Rad Laboratories,True,165,1816.57,NaN

In [12]:
df = df.dropna()

df = df.copy()
df.head()

,ID,Project Code,PQ #,PO _ SO #,ASN_DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure _Per Pack_,Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight _Kilograms_,Freight Cost _USD_,Line Item Insurance _USD_
2,6671,104-CI-T01,Pre-PQ Process,SCMS-609,ASN-704,Côte d'Ivoire,PMO - US,Direct Drop,CIP,Air,...,60,5721,145885.5,25.5,0.42,"BMS Meymac, France",True,1232,Freight Included in Commodity Cost,233.42
3,108,104-CI-T01,Pre-PQ Process,SCMS-698,ASN-727,Côte d'Ivoire,PMO - US,Direct Drop,CIP,Air,...,60,5513,140581.5,25.5,0.42,"BMS Meymac, France",True,2126,Freight Included in Commodity Cost,224.93
5,4302,104-CI-T01,Pre-PQ Process,SCMS-18280,ASN-1550,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,40,476,36176.0,76.0,1.90,Bio-Rad Laboratories,True,522,6924.83,57.88
6,391,104-CI-T01,Pre-PQ Process,SCMS-18290,ASN-1879,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,40,476,36176.0,76.0,1.90,Bio-Rad Laboratories,True,509,5446.51,57.88
7,5661,104-CI-T01,Pre-PQ Process,SCMS-19100,ASN-1598,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,40,331,25156.0,76.0,1.90,Bio-Rad Laboratories,True,366,7915.98,40.25

In [13]:
df['delay_days'] = (
    pd.to_datetime(df['Delivered to Client Date']) -
    pd.to_datetime(df['Scheduled Delivery Date'])
).dt.days

df[['delay_days']].head()

   delay_days
2           0
3           0
5           3
6           0
7           0